### PR TITLE
make "Type" enums nested

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by p4u** [comment]
Is this finished @mvdan ?

**Comment by mvdan** [comment]
Yes it is, but note that my JS commit removed package-lock.json for some reason. I only ran `make js`, so I assume that's okay?

**Comment by jordipainan** [comment]
I can readd it, it is something like the go.sum

**Comment by mvdan** [comment]
Maybe make `make js` keep it in, then? Otherwise it's quite likely it will be removed again :)

**Pull request merged**
