### PR TITLE
Added Avax and Fuji Support

### PR DESCRIPTION
**Pull request by maektwain**
Hey, i thought that adding build lib was mistake, but originally intentional 

Let me know if we can merge this. 

Thanks

### CODE REVIEW

**Comment by p4u** [comment]
Hello @maektwain, few things:
1. I'd prefer you to just send the PR adding the new lines to the sourceNetworkId ENUM, the CI will compile the bindings automatically once merged
2. That's just a first step to suporting Avalanche, I'm fine with it, but we should be sure our Smart Contracts deploy correctly there (@jordipainan?)
3. Can you send the same PR to release-1.2 branch (that's the one we are gonna deploy on production soon)

**Comment by maektwain** [comment]
1. removed build dir, 
2. Could you point me for further access to the Contracts, I can try deploying them and test them
3. Yeah i will do that thanks

**Comment by jordipainan** [comment]
Hi @maektwain ! You can find the contracts [here](https://github.com/vocdoni/dvote-solidity) :)

**Comment by maektwain** [comment]
I have few questions , 

1. Since the node connects with OpenEth and Parity to be able to connect with Avax , should we supply the dockerfile in the node codebase?

**Comment by p4u** [comment]
> I have few questions ,
> 
> 1. Since the node connects with OpenEth and Parity to be able to connect with Avax , should we supply the dockerfile in the node codebase?

Its not a requirement but it would help. 

The Oracle deployed to listen the events on Avax will need to connect to a Avax Web3 node (which can be remote such as infura or local via docker-compose).

**Pull request closed without merging**
